pluginManagement {
    apply from: 'gradle/repositories.gradle'

    repositories commonRepositories
    repositories {
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    apply from: 'gradle/repositories.gradle'

    repositories {
        mavenLocal()
    }
    repositories commonRepositories
}

include ':encoder',
        ':http',
        ':id',
        ':job',
        ':logger',
        ':storage',
        ':utils'
